# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: 2025 Erlang Ecosystem Foundation

name: "Mix SBoM"
description: "Calculates dependencies for Mix and outputs a CycloneDX File"
author: "Erlang Ecosystem Foundation"
branding:
  icon: arrow-up
  color: blue
inputs:
  project-path:
    required: true
    description: "Repo path to the mix.exs file used to detect dependencies. Defaults to mix.exs in the root of the repository."
    default: "${{ github.workspace }}"
  schema:
    required: true
    description: "CycloneDX Schema Version"
    default: "1.6"
  format:
    required: true
    description: "CycloneDX Output Format"
    default: "json"
  reuse-beam:
    required: false
    description: "Use local BEAM installation instead of pre-compiled binaries. Requires Elixir/Erlang to be set up beforehand."
    default: "false"
  include-system-dependencies:
    required: false
    description: "Include system dependencies (Erlang/OTP, Elixir, Hex) in the SBoM."
    default: "true"
outputs:
  sbom-path:
    description: "Path to the generated SBoM"
    value: "${{ steps.generate.outputs.output }}"
runs:
  using: "composite"
  steps:
    - name: "Install SBoM Tool"
      run: |
        set -e

        if [ "$REUSE_BEAM" = "true" ]; then
          mix escript.install \
            github "$REPO" \
            tag "$TAG" \
            --force

          echo "$HOME/.mix/escripts" >> "$GITHUB_PATH"
        else
          BIN_PATH="$(pwd)/mix_sbom_bin"

          mkdir "$BIN_PATH"

          gh release download \
            "$TAG" \
            --repo "$REPO" \
            --pattern "mix_sbom_${{ runner.os }}_${{ runner.arch }}" \
            --output "$BIN_PATH/mix_sbom"

          gh attestation verify \
            --repo "$REPO" \
            --source-ref "refs/tags/$TAG" \
            "$BIN_PATH/mix_sbom"

          chmod +x "$BIN_PATH/mix_sbom"

          echo "$BIN_PATH" >> "$GITHUB_PATH"
        fi
      shell: "bash"
      working-directory: "${{ runner.temp }}"
      env:
        TAG: "v0.9.0"
        GITHUB_TOKEN: ${{ github.token }}
        REPO: "erlef/mix_sbom"
        REUSE_BEAM: "${{ inputs.reuse-beam }}"
    - name: "Generate SBoM"
      id: generate
      run: |
        set -e

        OUTPUT_TEMP="$RUNNER_TEMP/$RANDOM.cdx.$FORMAT"

        mix_sbom \
          cyclonedx \
          --schema="$SCHEMA" \
          --format="$FORMAT" \
          --output="$OUTPUT_TEMP" \
          ${{ inputs.include-system-dependencies == 'true' && '' || '--exclude-system-dependencies' }} \
          "$PROJECT_PATH"

        echo "output=$OUTPUT_TEMP" >> "$GITHUB_OUTPUT"
      shell: "bash"
      env:
        PROJECT_PATH: "${{ inputs.project-path }}"
        SCHEMA: "${{ inputs.schema }}"
        FORMAT: "${{ inputs.format }}"
