defmodule SBoM.CycloneDX.V17.CryptoProperties.CertificateExtensions.CommonExtensionName do
  @moduledoc """
  Common extension names
  """

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.15.0", syntax: :proto3

  field(:COMMON_EXTENSION_NAME_UNSPECIFIED, 0)
  field(:COMMON_EXTENSION_NAME_BASIC_CONSTRAINTS, 1)
  field(:COMMON_EXTENSION_NAME_KEY_USAGE, 2)
  field(:COMMON_EXTENSION_NAME_EXTENDED_KEY_USAGE, 3)
  field(:COMMON_EXTENSION_NAME_SUBJECT_ALTERNATIVE_NAME, 4)
  field(:COMMON_EXTENSION_NAME_AUTHORITY_KEY_IDENTIFIER, 5)
  field(:COMMON_EXTENSION_NAME_SUBJECT_KEY_IDENTIFIER, 6)
  field(:COMMON_EXTENSION_NAME_AUTHORITY_INFORMATION_ACCESS, 7)
  field(:COMMON_EXTENSION_NAME_CERTIFICATE_POLICIES, 8)
  field(:COMMON_EXTENSION_NAME_CRL_DISTRIBUTION_POINTS, 9)
  field(:COMMON_EXTENSION_NAME_SIGNED_CERTIFICATE_TIMESTAMP, 10)
end
