defmodule SBoM.Cyclonedx.V14.ExternalReferenceType do
  @moduledoc false

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.15.0", syntax: :proto3

  field(:EXTERNAL_REFERENCE_TYPE_OTHER, 0)
  field(:EXTERNAL_REFERENCE_TYPE_VCS, 1)
  field(:EXTERNAL_REFERENCE_TYPE_ISSUE_TRACKER, 2)
  field(:EXTERNAL_REFERENCE_TYPE_WEBSITE, 3)
  field(:EXTERNAL_REFERENCE_TYPE_ADVISORIES, 4)
  field(:EXTERNAL_REFERENCE_TYPE_BOM, 5)
  field(:EXTERNAL_REFERENCE_TYPE_MAILING_LIST, 6)
  field(:EXTERNAL_REFERENCE_TYPE_SOCIAL, 7)
  field(:EXTERNAL_REFERENCE_TYPE_CHAT, 8)
  field(:EXTERNAL_REFERENCE_TYPE_DOCUMENTATION, 9)
  field(:EXTERNAL_REFERENCE_TYPE_SUPPORT, 10)
  field(:EXTERNAL_REFERENCE_TYPE_DISTRIBUTION, 11)
  field(:EXTERNAL_REFERENCE_TYPE_LICENSE, 12)
  field(:EXTERNAL_REFERENCE_TYPE_BUILD_META, 13)
  field(:EXTERNAL_REFERENCE_TYPE_BUILD_SYSTEM, 14)
end
