defmodule SBoM.CycloneDX.V15.ExternalReferenceType do
  @moduledoc "CycloneDX ExternalReferenceType model."
  use Protobuf,
    enum: true,
    full_name: "cyclonedx.v1_5.ExternalReferenceType",
    protoc_gen_elixir_version: "0.16.0",
    syntax: :proto3

  field(:EXTERNAL_REFERENCE_TYPE_OTHER, 0)
  field(:EXTERNAL_REFERENCE_TYPE_VCS, 1)
  field(:EXTERNAL_REFERENCE_TYPE_ISSUE_TRACKER, 2)
  field(:EXTERNAL_REFERENCE_TYPE_WEBSITE, 3)
  field(:EXTERNAL_REFERENCE_TYPE_ADVISORIES, 4)
  field(:EXTERNAL_REFERENCE_TYPE_BOM, 5)
  field(:EXTERNAL_REFERENCE_TYPE_MAILING_LIST, 6)
  field(:EXTERNAL_REFERENCE_TYPE_SOCIAL, 7)
  field(:EXTERNAL_REFERENCE_TYPE_CHAT, 8)
  field(:EXTERNAL_REFERENCE_TYPE_DOCUMENTATION, 9)
  field(:EXTERNAL_REFERENCE_TYPE_SUPPORT, 10)
  field(:EXTERNAL_REFERENCE_TYPE_DISTRIBUTION, 11)
  field(:EXTERNAL_REFERENCE_TYPE_LICENSE, 12)
  field(:EXTERNAL_REFERENCE_TYPE_BUILD_META, 13)
  field(:EXTERNAL_REFERENCE_TYPE_BUILD_SYSTEM, 14)
  field(:EXTERNAL_REFERENCE_TYPE_SECURITY_CONTACT, 15)
  field(:EXTERNAL_REFERENCE_TYPE_ATTESTATION, 16)
  field(:EXTERNAL_REFERENCE_TYPE_THREAT_MODEL, 17)
  field(:EXTERNAL_REFERENCE_TYPE_ADVERSARY_MODEL, 18)
  field(:EXTERNAL_REFERENCE_TYPE_RISK_ASSESSMENT, 19)
  field(:EXTERNAL_REFERENCE_TYPE_DISTRIBUTION_INTAKE, 20)
  field(:EXTERNAL_REFERENCE_TYPE_VULNERABILITY_ASSERTION, 21)
  field(:EXTERNAL_REFERENCE_TYPE_EXPLOITABILITY_STATEMENT, 22)
  field(:EXTERNAL_REFERENCE_TYPE_PENTEST_REPORT, 23)
  field(:EXTERNAL_REFERENCE_TYPE_STATIC_ANALYSIS_REPORT, 24)
  field(:EXTERNAL_REFERENCE_TYPE_DYNAMIC_ANALYSIS_REPORT, 25)
  field(:EXTERNAL_REFERENCE_TYPE_RUNTIME_ANALYSIS_REPORT, 26)
  field(:EXTERNAL_REFERENCE_TYPE_COMPONENT_ANALYSIS_REPORT, 27)
  field(:EXTERNAL_REFERENCE_TYPE_MATURITY_REPORT, 28)
  field(:EXTERNAL_REFERENCE_TYPE_CERTIFICATION_REPORT, 29)
  field(:EXTERNAL_REFERENCE_TYPE_QUALITY_METRICS, 30)
  field(:EXTERNAL_REFERENCE_TYPE_CODIFIED_INFRASTRUCTURE, 31)
  field(:EXTERNAL_REFERENCE_TYPE_MODEL_CARD, 32)
  field(:EXTERNAL_REFERENCE_TYPE_POAM, 33)
  field(:EXTERNAL_REFERENCE_TYPE_LOG, 34)
  field(:EXTERNAL_REFERENCE_TYPE_CONFIGURATION, 35)
  field(:EXTERNAL_REFERENCE_TYPE_EVIDENCE, 36)
  field(:EXTERNAL_REFERENCE_TYPE_FORMULATION, 37)
end
