# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: 2025 Erlang Ecosystem Foundation

name: "Test All CycloneDX Combinations"
description: "Tests all CycloneDX schema/format combinations for a given command"
inputs:
  command:
    description: "Command to generate SBoM (e.g., 'mix sbom.cyclonedx', './burrito_artifacts/mix_sbom_Linux_X64 cyclonedx')"
    required: true
  command-args:
    description: "Additional arguments to append to the command (e.g., '.' for escript/burrito)"
    required: false
    default: ""
  test-name:
    description: "Name for the test (used in log file and output)"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Install CycloneDX CLI"
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        echo "PATH=$PATH" >> "$GITHUB_ENV"
        brew tap cyclonedx/cyclonedx
        brew install cyclonedx/cyclonedx/cyclonedx-cli
      shell: bash

    - name: "Test All Combinations"
      env:
        COMMAND: ${{ inputs.command }}
        COMMAND_ARGS: ${{ inputs.command-args }}
        TEST_NAME: ${{ inputs.test-name }}
      run: |
        LOG_FILE="${TEST_NAME,,}_test.log"
        FAILED=0
        
        echo "=== $TEST_NAME Smoke Tests ===" > "$LOG_FILE"
        echo "" >> "$LOG_FILE"
        
        for CYCLONE_VERSION in "1.3" "1.4" "1.5" "1.6" "1.7"; do
          for FORMAT in "json" "xml" "protobuf"; do
            echo "--- Testing schema $CYCLONE_VERSION / format $FORMAT ---" >> "$LOG_FILE"
            
            if [ "$FORMAT" == "protobuf" ]; then
              OUTPUT_FILE="bom_${TEST_NAME,,}.cdx"
            else
              OUTPUT_FILE="bom_${TEST_NAME,,}.$FORMAT"
            fi
            
            echo -n "Schema $CYCLONE_VERSION, Format $FORMAT: "
            
            # Generate SBoM
            if $COMMAND \
              --schema "$CYCLONE_VERSION" \
              --format "$FORMAT" \
              --output "$OUTPUT_FILE" \
              $COMMAND_ARGS >> "$LOG_FILE" 2>&1; then
              
              # Validate SBoM
              if [ "$CYCLONE_VERSION" == "1.7" ]; then
                echo "⚠️ (validation skipped for 1.7)" >> "$LOG_FILE" 2>&1
                echo "⚠️ (validation skipped for 1.7)"
              elif [ "$FORMAT" == "protobuf" ]; then
                if cyclonedx convert \
                  --input-file "$OUTPUT_FILE" \
                  --output-file "$OUTPUT_FILE.json" \
                  --input-format protobuf \
                  --output-format json >> "$LOG_FILE" 2>&1 && \
                  cyclonedx validate --input-file "$OUTPUT_FILE.json" --input-format json --fail-on-errors >> "$LOG_FILE" 2>&1; then
                  rm -f "$OUTPUT_FILE.json"
                  echo "✓"
                else
                  rm -f "$OUTPUT_FILE.json"
                  echo "✗"
                  FAILED=1
                fi
              else
                if cyclonedx validate --input-file "$OUTPUT_FILE" --input-format "$FORMAT" --fail-on-errors >> "$LOG_FILE" 2>&1; then
                  echo "✓"
                else
                  echo "✗"
                  FAILED=1
                fi
              fi
            else
              echo "✗"
              FAILED=1
            fi
            
            rm -f "$OUTPUT_FILE"
            echo "" >> "$LOG_FILE"
          done
        done
        
        if [ "$FAILED" -eq 1 ]; then
          echo ""
          echo "=== FAILURES DETECTED - Full Log ==="
          cat "$LOG_FILE"
          exit 1
        fi
      shell: bash