# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: 2025 Erlang Ecosystem Foundation

name: "Setup Application Runtime Environment"
description: "Setup Application Runtime Environment"
inputs:
  mix-env:
    description: "Mix environment to use"
    required: false
    default: "dev"
  elixir-version:
    description: "Elixir version to install"
    required: false
    default: ""
  otp-version:
    description: "OTP version to install"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: "Setup BEAM"
      uses: erlef/setup-beam@5304e04ea2b355f03681464e683d92e3b2f18451 # v1.18.2
      with:
        version-file: "${{ !inputs.elixir-version && !inputs.otp-version && '.tool-versions' || '' }}"
        version-type: strict
        elixir-version: "${{ inputs.elixir-version }}"
        otp-version: "${{ inputs.otp-version }}"

    - name: "Cache Deps / Build"
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |-
          deps
          _build
        key: "${{ format('{0}-{1}-{2}-{3}-{4}', inputs.mix-env, hashFiles('.tool-versions'), inputs.otp-version, inputs.elixir-version, hashFiles('mix.exs')) }}"
        restore-keys: "${{ format('{0}-{1}-{2}-{3}-', inputs.mix-env, hashFiles('.tool-versions'), inputs.otp-version, inputs.elixir-version) }}"

    - name: "Install Dependencies"
      run: mix deps.get --check-locked
      shell: bash

    - name: "Compile Dependencies"
      run: mix deps.compile
      shell: bash

    - name: "Compile Application"
      run: mix compile --warning-as-errors
      shell: bash
