defmodule SBoM.CycloneDX.V17.Classification do
  @moduledoc "CycloneDX Classification model."
  use Protobuf, enum: true, protoc_gen_elixir_version: "0.15.0", syntax: :proto3

  field(:CLASSIFICATION_NULL, 0)
  field(:CLASSIFICATION_APPLICATION, 1)
  field(:CLASSIFICATION_FRAMEWORK, 2)
  field(:CLASSIFICATION_LIBRARY, 3)
  field(:CLASSIFICATION_OPERATING_SYSTEM, 4)
  field(:CLASSIFICATION_DEVICE, 5)
  field(:CLASSIFICATION_FILE, 6)
  field(:CLASSIFICATION_CONTAINER, 7)
  field(:CLASSIFICATION_FIRMWARE, 8)
  field(:CLASSIFICATION_DEVICE_DRIVER, 9)
  field(:CLASSIFICATION_PLATFORM, 10)
  field(:CLASSIFICATION_MACHINE_LEARNING_MODEL, 11)
  field(:CLASSIFICATION_DATA, 12)
  field(:CLASSIFICATION_CRYPTOGRAPHIC_ASSET, 13)
end
