defmodule SBoM.CycloneDX.V17.ImpactAnalysisJustification do
  @moduledoc "CycloneDX ImpactAnalysisJustification model."
  use Protobuf,
    enum: true,
    full_name: "cyclonedx.v1_7.ImpactAnalysisJustification",
    protoc_gen_elixir_version: "0.16.0",
    syntax: :proto3

  field(:IMPACT_ANALYSIS_JUSTIFICATION_NULL, 0)
  field(:IMPACT_ANALYSIS_JUSTIFICATION_CODE_NOT_PRESENT, 1)
  field(:IMPACT_ANALYSIS_JUSTIFICATION_CODE_NOT_REACHABLE, 2)
  field(:IMPACT_ANALYSIS_JUSTIFICATION_REQUIRES_CONFIGURATION, 3)
  field(:IMPACT_ANALYSIS_JUSTIFICATION_REQUIRES_DEPENDENCY, 4)
  field(:IMPACT_ANALYSIS_JUSTIFICATION_REQUIRES_ENVIRONMENT, 5)
  field(:IMPACT_ANALYSIS_JUSTIFICATION_PROTECTED_BY_COMPILER, 6)
  field(:IMPACT_ANALYSIS_JUSTIFICATION_PROTECTED_AT_RUNTIME, 7)
  field(:IMPACT_ANALYSIS_JUSTIFICATION_PROTECTED_AT_PERIMETER, 8)
  field(:IMPACT_ANALYSIS_JUSTIFICATION_PROTECTED_BY_MITIGATING_CONTROL, 9)
end
