defmodule SBoM.CycloneDX.V17.CryptoProperties.AlgorithmProperties.CryptoImplementationPlatform do
  @moduledoc """
  Implementation platform
  """

  use Protobuf,
    enum: true,
    full_name: "cyclonedx.v1_7.CryptoProperties.AlgorithmProperties.CryptoImplementationPlatform",
    protoc_gen_elixir_version: "0.16.0",
    syntax: :proto3

  field(:CRYPTO_IMPLEMENTATION_PLATFORM_UNSPECIFIED, 0)
  field(:CRYPTO_IMPLEMENTATION_PLATFORM_UNKNOWN, 1)
  field(:CRYPTO_IMPLEMENTATION_PLATFORM_OTHER, 2)
  field(:CRYPTO_IMPLEMENTATION_PLATFORM_GENERIC, 3)
  field(:CRYPTO_IMPLEMENTATION_PLATFORM_X86_32, 4)
  field(:CRYPTO_IMPLEMENTATION_PLATFORM_X86_64, 5)
  field(:CRYPTO_IMPLEMENTATION_PLATFORM_ARMV7A, 6)
  field(:CRYPTO_IMPLEMENTATION_PLATFORM_ARMV7M, 7)
  field(:CRYPTO_IMPLEMENTATION_PLATFORM_ARMV8A, 8)
  field(:CRYPTO_IMPLEMENTATION_PLATFORM_ARMV8M, 9)
  field(:CRYPTO_IMPLEMENTATION_PLATFORM_ARMV9A, 10)
  field(:CRYPTO_IMPLEMENTATION_PLATFORM_ARMV9M, 11)
  field(:CRYPTO_IMPLEMENTATION_PLATFORM_X390X, 12)
  field(:CRYPTO_IMPLEMENTATION_PLATFORM_PPC64, 13)
  field(:CRYPTO_IMPLEMENTATION_PLATFORM_PPC64LE, 14)
end
