# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: 2026 Erlang Ecosystem Foundation

on:
  workflow_call: {}

name: "Attest SBOM"

permissions:
  contents: read

jobs:
  attest:
    name: "Attest Build Artifacts with SBOM"

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - name: "Download Docs Artifact"
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: docs
          path: .

      - name: "Download Binary Artifact"
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: binary
          path: .

      - name: "Download Source SBoM Artifact"
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: sbom
          path: .

      - name: "Attest build artifacts with SBOM"
        uses: actions/attest-sbom@c604332985a26aa8cf1bdc465b92731239ec6b9e # v4.1.0
        with:
          subject-path: |
            docs.tar.gz
            mix_sbom_*
          sbom-path: sbom.spdx.json
